name: CI
on: [push]

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: set -o pipefail && xcodebuild -project UTIKit.xcodeproj -scheme 'UTIKit iOS' -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=13.5,name=iPhone 11 Pro' test | xcpretty
  release:
    name: Release
    needs: [test]
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.5.app
    if: contains(github.ref, 'tags/')
    steps:
    - uses: actions/checkout@v2
    - name: Push
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: pod trunk push UTIKit.podspec
